name: ArduinoIntegration
main: de.neosit.minecraft.arduinointegration.Main
version: '1'
author: tobias.hellman@neos-it.de, meikel.philipp@neos-it.de
description: Integrate an Arduino to Minecraft
commands:
  arduino:
    description: Commands to control the plugin or the arduino itself
    aliases: ["arduino --help", "arduino -h", "arduino ?"]
