name: ArduinoIntegration
main: de.neosit.minecraft.arduinointegration.Main
version: '1'
author: tobias.hellman@neos-it.de, meikel.philipp@neos-it.de
description: Integrate an Arduino to Minecraft
commands:
  arduino:
    description: Commands to control the plugin or the arduino itself
    aliases: ["arduino --help", "arduino -h", "arduino ?"]
  arduino send:
    description: Use §9/arduino send [ARGS]§r to send a message to the arduino.
  arduino reload:
    description: |
      Use §9/arduino reload [CONFIG]§r to reload a specific configuration file of this plugin.
      Available configration files are:
      §9config
